spring:
  application:
    name: seoul-nolgoat
  config:
    import:
      - db-config.yml
      - kakao-config.yml
      - seoul-config.yml
      - t-config.yml
      - oauth2-config.yml
      - jwt-config.yml
      - s3-config.yml